### ISSUE TITLE
Logstash compressed messages

### ISSUE THREAD

**Issue by b-hass** [elastic/go-lumber#14]
Greetings!

I'm implementing a Filebeats reader with the lumberjack protocol in Elixir.

What I've noticed so far is that upon connection Filebeat sends me a Window frame together with a Compressed one. These ones I manage to parse, inflate and read several JSON events. But after that Filebeats sends me a bunch of weird frames not mentioned anywhere in the protocol docs. Are those frames the continuation of the first compressed one filebeats sent me? I thoght I would receive only "whole frames" to parse thanks to TCP. Am I getting something wrong here?

Thanks a lot for you attention!

**Comment by andresrc** [comment]
ping @elastic/integrations-services

**Comment by urso** [comment]
TCP is a streaming protocol, which means that one likely needs multiple `read` calls on the socket in order to consume a single batch. The lumberjack protocol sits right on top of TCP and adds some framing, so we can separate batches and events from each other. Beats do not put any extra byte on the wire.

> I thoght I would receive only "whole frames" to parse thanks to TCP

TCP has no concept of frames. The "contract" between TCP and upper layers requires readers/writers to treat TCP as a byte stream. The protocol implementor/developer needs to handle the framing logic and required buffering themselves. Only layers on top of the lumberjack protocol can expect complete events.

You can find a sample server batch read loop [here](https://github.com/elastic/go-lumber/blob/master/server/v2/reader.go#L55). The code continuously calls `readFull` with a buffer of known size in order to read the next N bytes from the (normally buffered) input stream.

**Comment by b-hass** [comment]
I guess I'm going to write an abstraction layer to acumulate bytes then.

Thanks a lot @urso. That was very clarifying.
